apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mobile-deposit-api-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mobile-deposit-api
    spec:
      containers:
      - name: mobile-deposit-api
        image: ${env.DOCKER_REGISTRY}/mobile-deposit-api:${dockerTag}
        ports:
        - containerPort: 8080
