apiVersion: v1
kind: Service
metadata:
  name: mobile-deposit-api-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mobile-deposit-api-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mobile-deposit-api
    spec:
      containers:
      - name: mobile-deposit-api
        image: ${env.DOCKER_REGISTRY}/mobile-deposit-api:${dockerTag}
        ports:
        - containerPort: 8080
