apiVersion: v1
kind: Service
metadata:
  name: mobile-deposit-api-service
spec:
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mobile-deposit-api-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mobile-deposit-api
    spec:
      containers:
      - name: mobile-deposit-api
        image: REGISTRY_NAME/mobile-deposit-api:IMAGE_TAG
        ports:
        - containerPort: 8080
