apiVersion: v1
kind: Service
metadata:
  name: mobile-deposit-api
  labels:
    app: mobile-deposit-api
spec:
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: mobile-deposit-api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mobile-deposit-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mobile-deposit-api
    spec:
      containers:
      - name: mobile-deposit-api
        image: REGISTRY_NAME/mobile-deposit-api:IMAGE_TAG
        ports:
        - containerPort: 8080
